version: '3'

networks:
  comicapinode.networks:
    driver: bridge

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://mariadb:3306 -wait tcp://redis:6379 -timeout 10s ./.docker/scripts/entrypoint.sh
    container_name: comicapinode.app
    tty: true
    depends_on:
      - redis
      - mariadb
    networks:
      - comicapinode.networks
    volumes:
      - .:/home/node/app:z
    ports:
      - 3333:3333

  nginx:
    build: .docker/nginx
    container_name: comicapinode.nginx
    restart: always
    tty: true
    depends_on:
      - app
      - mariadb
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - .:/home/node/app:z
    networks:
      - comicapinode.networks

  #  mysql:
  #    image: mysql:8
  #    container_name: comicapinode.mysql
  #    tty: true
  #    networks:
  #      - comicapinode.networks
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - .docker/mysql:/var/lib/mysql
  #    environment:
  #      MYSQL_USER: root
  #      MYSQL_PASSWORD: root
  #      MYSQL_DATABASE: development
  #      MYSQL_ROOT_PASSWORD: root

  mariadb:
    image: mariadb
    tty: true
    restart: always
    container_name: comicapinode.mariadb
    networks:
      - comicapinode.networks
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:z
      - .docker/mysql/data:/var/lib/mysql:z
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  #  postgres:
  #    build: .docker/postgres
  #    tty: true
  #    restart: always
  #    container_name: comicapinode.postgres
  #    networks:
  #      - comicapinode.networks
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - .docker/postgres/dbdata:/var/lib/postgresql/data:z
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=root
  #      - POSTGRES_DB=development

  redis:
    image: bitnami/redis:latest
    container_name: comicapinode.redis
    tty: true
    networks:
      - comicapinode.networks
    ports:
      - 6379:6379
    volumes:
      - .docker/redis:/bitnami/redis/data:z
    environment:
      REDIS_PASSWORD: redis
      ALLOW_EMPTY_PASSWORD: 'no'
